config/routes.rb
TripBudgetRails::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'

  resources :trips do
    resources :budgets, only: [:edit, :update] do
      resources :expenses
    end
  end

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  attr_accessible :category_id, :total, :trip_id
  belongs_to :trip
  belongs_to :category
  has_many :expenses

  validates_presence_of :category_id, :total

  default_scope order("created_at ASC")

  def name
    self.category.name
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :budgets
  has_many :trips, through: :budgets
  has_many :expenses, through: :budgets
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :amount, :budget_id, :trip_id, :name
  belongs_to :budget
  belongs_to :trip
  # has_one :category, through: :budgets

  validates_presence_of :amount, :name
end

app/models/trip.rb
require_relative 'category.rb'

class Trip < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user

  has_many :budgets, :dependent => :destroy
  has_many :expenses, :dependent => :destroy
  has_many :categories, through: :budgets

  validates_presence_of :user, :name
  validates_uniqueness_of :name, scope: :user_id, message: "must be unique"

  after_create :populate_budgets

  default_scope order("created_at ASC")

  private


  def populate_budgets
    Category.all.each do |category|
      self.budgets.create( total: 0, category_id: category.id )
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def edit
    @trip = Trip.find( params[:trip_id] )
    @budget = @trip.budgets.find( params[:id] )
  end

  def update
    @trip = Trip.find( params[:trip_id] )
    @budget = @trip.budgets.find( params[:id] )
    if @budget.update_attributes( params[:budget] )
      redirect_to(@trip,
        :notice => "#{@budget.name} budget was updated")
    else
      flash[:notice] = "Total amount must be given"
      render :edit
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @budget = Budget.find( params[:budget_id] )
  end

  def new
    @trip = Trip.find( params[:trip_id] )
    @budget = Budget.find( params[:budget_id] )
    @expense = @budget.expenses.new
  end

  def create
    @trip = Trip.find( params[:trip_id] )
    @budget = Budget.find( params[:budget_id] )
    @expense = @budget.expenses.new( params[:expense] )
    if @expense.save
      redirect_to(trip_path(@trip),
        :notice => "Expense added")
    else
      flash[:notice] = @expense.errors.full_messages.join(",")
      render :new
    end
  end

  def destroy
    @trip = Trip.find( params[:trip_id] )
    @expense = Expense.find( params[:id] )
    @expense.destroy
      redirect_to(trip_path(@trip),
        :notice => "Your expense was deleted")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :find_trip, :only => [:show, :edit, :update, :destroy]


  def index
    @trips = current_user.trips.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trips = current_user.trips.all
    @trip = current_user.trips.build(params[:trip])
    if @trip.save
      redirect_to(trip_path(@trip),
        :notice => "Your #{@trip.name} trip was created!")
    else
      flash[:notice] = @trip.errors.full_messages.join(",")
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @trip.update_attributes( params[:trip] )
      redirect_to(trips_path,
        :notice => "Your trip was updated")
    else
      flash[:notice] = @trip.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to(trips_path,
      :notice => "Your trip was deleted")
  end

  def find_trip
    @trip = current_user.trips.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/budgets/edit.html.erb
<div class="hero-unit-welcome">
  <h1>Set your budget</h1>
  <hr>
  <p class="message"><em>Edit your budget amount below</em></p>
  <%= form_for [@trip, @budget] do |f| %>
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="inputBudgetName">
          <%= f.label :total, "#{@budget.name} Total" %>
        </label>
        <div class="controls input-prepend input-append">
          <span class="add-on">$</span>
          <%= f.text_field :total, class: "span2" %>
          <span class="add-on">.00</span>
        </div><!-- end .controls -->
      </div><!-- end .control-group -->
      <div class="control-group clearfix">
        <div class="form">
          <%= link_to "Back", @trip, class: "btn cancel" %>
        </div>
        <div class="form">
          <%= f.submit "Save", class: "btn btn-primary submit" %>
        </div>
      </div><!-- end .control-group -->
    </form>
  <% end %>
</div><!-- end .hero-unit -->

app/views/expenses/new.html.erb
<div class="hero-unit-welcome">
  <h1><%= @budget.name %> Expenses</h1>
  <hr>
  <!-- category icon goes here -->
  <%= form_for [@trip, @budget, @expense] do |f| %>
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="inputExpenseName">
          <%= f.label :name, "Expense Name" %>
        </label>
        <div class="controls expense_name">
          <%= f.text_field :name %>
        </div>
        <label class="control-label" for="inputExpenseAmount">
          <%= f.label :amount, "Expense Amount" %>
        </label>
        <div class="controls input-prepend input-append expense_amount">
          <span class="add-on">$</span>
          <%= f.text_field :amount, class: "span2" %>
          <span class="add-on">.00</span>
        </div>
      </div><!-- end .control-group -->
      <div class="control-group clearfix">
        <div class="form">
          <%= link_to "Cancel", :back, class: "btn cancel" %>
        </div>
        <div class="form">
          <%= f.submit "Save", class: "btn btn-primary submit" %>
        </div>
      </div><!-- end .control-group -->
    </form>
  <% end %>
</div><!-- end .hero-unit -->

app/views/home/index.html.erb
<div class="hero-unit-welcome">
  <%- if flash[:notice] %>
    <li class="alert"><%= notice %></li>
  <% end %>
  <%- if flash[:alert] %>
    <li class="alert"><%= alert %></li>
  <% end %>
  <h1>Welcome to Trip Budget</h1>
  <% if user_signed_in? %>
    <div class="links btn">
      <%= link_to "Create a Trip", new_trip_path %>
    </div>
      <br />
    <div class="links btn">
      <%= link_to "View Trips", trips_path %>
    </div>
  <% else %>
    <div class="home_body">
      <p><b>Please sign in to view your profile</b></p><br />
      <div class="links btn">
        <%= link_to "Sign In", new_user_session_path %>
      </div>
      <div class="links btn">
        <%= link_to "Sign Up", new_user_registration_path %>
      </div>
    </div>
  <% end %>
</div><!-- end of .hero-unit -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset= "utf-8">
    <meta content= "width=device-width, initial-scale=1.0", name= "viewport">
    <title>Trip Budget</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <% if user_signed_in? %>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container-fluid">
            <div class="user_links">
              <%= link_to "Settings", edit_user_registration_path %>
              |
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              <div class="nav-collapse collapse">
                <p class="navbar-text pull right">Logged in <%= current_user.email %></p>
              </div>
            </div><!-- end of user_links -->
          </div>
        </div>
      </div>
    <% end %>
    <div id="main" role= "main">
      <div class="container-fluid">
        <div class="content">
          <div class="row-fluid">
            <div class="span12">


              <%= yield %>

            </div><!-- end of .span12 -->
          </div><!-- end of .row -->
          <footer>
          </footer>
        </div><!-- end of .content -->
      </div><!-- end of .container -->
    </div><!-- end of #main -->
  </body>
</html>

app/views/trips/edit.html.erb
<div class="hero-unit-welcome">
  <h1>Edit Trip</h1>
  <hr>
  <p class="message">Edit your trip below and save</p>
  <%= form_for @trip do |f| %>
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="inputTrip">
          <%= f.label :name, "Trip Name", class: "trip-label" %>
        </label>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group clearfix">
          <div class="form">
            <%= link_to "Cancel", trips_path, class: "btn cancel" %>
          </div>
          <div class="form">
            <%= f.submit "Update Trip", class: "btn btn-primary submit" %>
          </div>
      </div>
    </form>
  <% end %>
</div>

app/views/trips/index.html.erb
<div class="hero-unit-trips">
  <%- if flash[:notice] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">x</button><strong><%= notice %></strong>
    </div>
  <% end %>
  <%- if flash[:alert] %>
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">x</button><strong><%= alert %></strong>
    </div>
  <% end %>
  <h1>Your Trip List</h1>
  <hr>
  <%- if @trips.empty? %>
    <div class="home_body" >
      <em>There are no trips at this time</em>
    </div>
  <% else %>
    <table class="table trips-table">
      <tbody>
        <p class="table-message">
          <em>Click trip name to view</em>
        </p>
        <%- @trips.each do |trip| %>
          <tr>
            <td class="trip-name"><%= link_to trip.name, trip_path(trip)%></td>
            <td class="btn"><%= link_to "Edit", edit_trip_path(trip), id: "edit_trip_#{trip.id}"%></td>
            <td class="btn btn-danger"><%= link_to "Delete", trip, id: "delete_trip_#{trip.id}", :method => :delete%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <br />
  <%= link_to "New Trip", new_trip_path, class: "btn trips-links" %>
  <br />
  <br />
  <%= link_to "Home", :root, class: "btn trips-links" %>
</div><!-- end .hero-unit -->

app/views/trips/new.html.erb
<div class="hero-unit-welcome">
  <h1>Create a Trip</h1>
  <hr>
  <br />
  <%= form_for @trip do |f| %>
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label">
          <%= f.label :name, "Trip Name" %>
        </label>
        <div class="controls">
          <%= f.text_field :name %>
        </div><!-- end .controls -->
      </div><!-- end .control-group -->
      <div class="control-group clearfix">
        <div class="form">
          <%= link_to "Cancel", trips_path, class: "btn cancel" %>
        </div>
        <div class="form">
          <%= f.submit "Save Trip!", class: "btn btn-primary submit" %>
        </div>
      </div>
    </form>
  <% end %>
</div><!-- end .hero-unit -->

app/views/trips/show.html.erb
<div class="hero-unit-budget">
  <%- if flash[:notice] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">x</button><strong><%= notice %></strong>
    </div>
  <%- end %>
  <%- if flash[:alert] %>
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">x</button><strong><%= alert %></strong>
    </div>
  <%- end %>
  <h1 class="trip_name"><%= @trip.name %></h1>
  <h3 class="grand_total">Total Budget: $<%= @trip.budgets.sum(:total) %></h3>
  <br />
</div><!-- end .hero-unit -->
<div class="container-fluid">
  <div class="content">
    <!-- <div class="container budget-total-container"></div> -->
    <br />
    <br />

    <div class="container-fluid budget-container">

      <div class="row-fluid budget-row">
        <%- @trip.budgets[0..3].each do |budget| %>
          <div class="span3 budget-card">
            <table id="budget_category_<%= budget.name %>" class="table budget-table">
              <thead class="info">
                <tr>
                  <th class="table-head"><%= link_to budget.name, edit_trip_budget_path(budget,
                   :trip_id => @trip.id) %> Budget:</th>
                  <th class="table-head">$<%= budget.total %></th>
                </tr>
              </thead>
              <tbody>
                <%- budget.expenses.each do |expense| %>
                  <tr>
                    <td><%= expense.name %></td>
                    <td class="budget-expense">-<%= expense.amount %></td>
                    <td><%= link_to "Delete", [@trip, budget, expense], id: "delete_trip_budget_expense_#{expense.id}", :method => :delete, class: "btn-small btn-danger" %></td>
                  </tr>
                <%- end %>
                <%- if budget.total > 0 %>
                  <%- if budget.total > budget.expenses.sum(:amount) %>
                    <tr class="success">
                  <%- else %>
                    <tr class="error">
                  <%- end %>
                      <td>Balance:</td>
                      <td class="budget_balance">$<%= budget.total - budget.expenses.sum(:amount) %></td>
                    </tr>
                    <tr class="expense_button">
                      <td><%= link_to "Add Expense", new_trip_budget_expense_path( @trip, budget ), class: "btn-small btn-primary" %></td>
                    </tr>
                <%- else %>
                  <tr>
                    <td class="budget_message">Click <%= budget.name %> to add a budget</td>
                  </tr>
                <%- end %>
              </tbody>
            </table>
          </div><!-- end span3 -->
        <%- end %>
      </div><!-- end row -->


      <div class="row-fluid budget-row">
        <%- @trip.budgets[4..6].each do |budget| %>
          <div class="span3 budget-card">
            <table id="budget_category_<%= budget.name %>" class="table budget-table">
              <thead class="table-head">
                <tr>
                  <th><%= link_to budget.name, edit_trip_budget_path(budget,
                   :trip_id => @trip.id) %> Budget:</th>
                  <th>$<%= budget.total %></th>
                </tr>
              </thead>
              <tbody>
                <%- budget.expenses.each do |expense| %>
                  <tr>
                    <td><%= expense.name %></td>
                    <td class="budget-expense">-<%= expense.amount %></td>
                    <td><%= link_to "Delete", [@trip, budget, expense], id: "delete_trip_budget_expense_#{expense.id}", :method => :delete, class: "btn-small btn-danger" %></td>
                  </tr>
                <%- end %>
                <%- if budget.total > 0 %>
                  <%- if budget.total > budget.expenses.sum(:amount) %>
                    <tr class="success">
                  <%- else %>
                    <tr class="error">
                  <%- end %>
                      <td>Balance:</td>
                      <td class="budget_balance">$<%= budget.total - budget.expenses.sum(:amount) %></td>
                    </tr>
                    <tr class="expense_button">
                      <td><%= link_to "Add Expense", new_trip_budget_expense_path( @trip, budget ), class: "btn-small btn-primary" %></td>
                    </tr>
                <%- else %>
                  <tr>
                    <td class="budget_message">Click <%= budget.name %> to add a budget</td>
                  </tr>
                <%- end %>
              </tbody>
            </table>
          </div><!-- end span3 -->
        <%- end %>
      </div>
    <!-- </div> -->
    <!-- </div> --><!-- end .budget-container -->
    <div class="footer">
      <div>
        <%= link_to "Back", trips_path, class: "btn" %>
        |
        <%= link_to "Home", :root, class: "btn" %>
      </div><!-- end .links -->
    </div><!-- end .footer -->
  </div><!-- end .content -->
</div><!-- end .container -->